CREATE TABLE IF NOT EXISTS "user" ("id" text PRIMARY KEY NOT NULL,"name" text NOT NULL,"email" text NOT NULL UNIQUE,"email_verified" boolean DEFAULT false NOT NULL,"image" text,"created_at" timestamp with time zone NOT NULL,"updated_at" timestamp with time zone NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "session" ("id" text PRIMARY KEY NOT NULL,"expires_at" timestamp with time zone NOT NULL,"token" text NOT NULL UNIQUE,"created_at" timestamp with time zone NOT NULL,"updated_at" timestamp with time zone NOT NULL,"ip_address" text,"user_agent" text,"user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account" ("id" text PRIMARY KEY NOT NULL,"account_id" text NOT NULL,"provider_id" text NOT NULL,"user_id" text NOT NULL REFERENCES "user"("id") ON DELETE cascade,"access_token" text,"refresh_token" text,"id_token" text,"access_token_expires_at" timestamp with time zone,"refresh_token_expires_at" timestamp with time zone,"scope" text,"password" text,"created_at" timestamp with time zone NOT NULL,"updated_at" timestamp with time zone NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verification" ("id" text PRIMARY KEY NOT NULL,"identifier" text NOT NULL,"value" text NOT NULL,"expires_at" timestamp with time zone NOT NULL,"created_at" timestamp with time zone,"updated_at" timestamp with time zone);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "categories" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"slug" text NOT NULL UNIQUE,"name" text NOT NULL,"tagline" text NOT NULL,"description" text NOT NULL,"image_path" text NOT NULL,"display_order" integer DEFAULT 0 NOT NULL,"active" boolean DEFAULT true NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "banners" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"desktop_image" text NOT NULL,"mobile_image" text NOT NULL,"title" text,"link" text,"display_order" integer DEFAULT 0 NOT NULL,"active" boolean DEFAULT true NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "products" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,"category_id" uuid NOT NULL REFERENCES "categories"("id") ON DELETE cascade,"subcategory" text NOT NULL,"subcategory_slug" text NOT NULL,"title" text NOT NULL,"slug" text NOT NULL UNIQUE,"image_path" text NOT NULL,"link" text,"display_order" integer DEFAULT 0 NOT NULL,"active" boolean DEFAULT true NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL);
